# Generated by Django 4.1.4 on 2022-12-24 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
