# Generated by Django 4.1.4 on 2022-12-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
