# Generated by Django 4.1.4 on 2022-12-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='is_reserved',
            field=models.BooleanField(default=1),
        ),
    ]
