# Generated by Django 4.1.4 on 2022-12-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_is_reserved'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
    ]
