# Generated by Django 4.1.4 on 2022-12-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
