# Generated by Django 4.1.4 on 2022-12-24 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True)),
                ('seat', models.IntegerField(default=1, max_length=12, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
