# Generated by Django 4.1.4 on 2022-12-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_table_seat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
    ]
